### ISSUE TITLE
v5 Noah HRLDAS Driver broken for MPI

### ISSUE THREAD

**Issue by bfkg** [NCAR/wrf_hydro_nwm_public#268]
## Expected Behavior

Runs without stopping.

## Current Behavior
Stops for Land_model MPI init and later for timestepping due to uninitialized variables on ranks > 0

## Possible Solution
for mpi init problem
change

    subroutine MPP_LAND_INIT()
    !    ### initialize the land model logically based on the two D method. 
    !    ### Call this function directly if it is nested with WRF.
    implicit none
    integer :: ierr, provided
    integer :: ew_numprocs, sn_numprocs  ! input the processors in x and y direction.
    logical mpi_inited

    !     left_right_np = ew_numprocs
    !     up_down_np  = sn_numprocs

      CALL mpi_initialized( mpi_inited, ierr )
      if ( .NOT. mpi_inited ) then
           call MPI_INIT_THREAD( MPI_THREAD_FUNNELED, provided, ierr )  ! stand alone land model.
           HYDRO_COMM_WORLD = MPI_COMM_WORLD
       endif
           call MPI_COMM_RANK( HYDRO_COMM_WORLD, my_id, ierr )
           call MPI_COMM_SIZE( HYDRO_COMM_WORLD, numprocs, ierr )
    !     create 2d logical mapping of the CPU.
         call log_map2d()
         return
      end   subroutine MPP_LAND_INIT

so that HYDRO_COMM_WORLD becomes a ducplicate of MPI_COMM_WORLD also if MPI had already been initialized.

    subroutine MPP_LAND_INIT()
    !    ### initialize the land model logically based on the two D method. 
    !    ### Call this function directly if it is nested with WRF.
    implicit none
    integer :: ierr, provided
    integer :: ew_numprocs, sn_numprocs  ! input the processors in x and y direction.
    logical mpi_inited

    !     left_right_np = ew_numprocs
    !     up_down_np  = sn_numprocs

      CALL mpi_initialized( mpi_inited, ierr )
      if ( .NOT. mpi_inited ) then
           call MPI_INIT_THREAD( MPI_THREAD_FUNNELED, provided, ierr )  ! stand alone land model.
           HYDRO_COMM_WORLD = MPI_COMM_WORLD
       endif
           HYDRO_COMM_WORLD = MPI_COMM_WORLD
           call MPI_COMM_RANK( HYDRO_COMM_WORLD, my_id, ierr )
           call MPI_COMM_SIZE( HYDRO_COMM_WORLD, numprocs, ierr )
    !     create 2d logical mapping of the CPU.
         call log_map2d()
         return
      end   subroutine MPP_LAND_INIT

For timestepping problem  ranks > 0 need proper initialization for HRLDAS namelist variables in 
**Land_models/Noah/IO_code/Noah_hrldas_driver.F**

## Steps to Reproduce (for bugs)

1. compile noah (classic) version
2. use ideal forcing or v5 testcase
3. use mpirun -n > 1

## Your Environment

* Version of the code used: v5.1.0-alpha11 but also happens for v5.0
* Operating System and version: linux (debian and rhl)
* Compiler and version: (intel-mpich)
* Other relevant information:

**Comment by kafitzgerald** [comment]
Apologies for lack of responsiveness on this.  I thought it had been addressed with some of the MPI changes that went in earlier this year, but it appears to be unrelated. 

That said I wasn't able to replicate this with WRF-Hydro v5.1 code, but did notice a similar MPI initialization error with typos in the HRLDAS namelist.  I wonder if this may be the case here as well.  I would be happy to take a look.   

It's possible there might also be problems running Noah with the test cases because of how wrfinput files are created for those (i.e. without running the full WPS + real and therefore missing some Noah-only variables).  That said, the coupled test case runs cleanly with WRF-Hydro standalone using Noah and idealized forcing and the standalone Gridded_no_lakes domain does run without error.  

I'm going to close this for now, but please reopen if errors persist.
