### ISSUE TITLE
Error in reading hydro.namelist

### ISSUE THREAD

**Issue by arezoorn** [NCAR/wrf_hydro_nwm_public#440]
I pulled the master (this commit: commit 8f248ef1b6b639214ebafed41e3cfd7e4d216b76) and compiled and tried to run an example which failed reading the hydronamelist. If I comment out the reservoir part of the namelist, it will work.  

## Expected Behavior
The model run with the namelist/hydronamelist distributed with the git repository. 

## Current Behavior
It fails to read the hydro.namelist because of the reservoir entries:
! If using Persistence Reservoirs, set to True. (Default=.FALSE.)
reservoir_persistence = .FALSE.

! Specify the Persistence Reservoir parameter file
reservoir_parameter_file = "./DOMAIN/persistence_parm.nc"

! Specify the path to the Timeslice files to be used by Reservoirs
reservoir_timeslice_path = "./Timeslices/"

! Specify lookback hours to read reservoir observation data
reservoir_observation_lookback_hours = 18

! Specify update time interval in seconds to read new reservoir observation data
! The default is 86400 (seconds per day) in retrospective mode and 1000000000 in all forecast modes
reservoir_observation_update_time_interval_seconds = 86400

## Possible Solution
If the master does not have the reservoir code, then the hydro.namelist distributed with the code should not have the reservoir entries in the hydro.namelist.

## Steps to Reproduce (for bugs)
There is a test case, located here: /glade/u/home/arezoo/scratch/Lindsay
There are two hydronamelist. One works when commenting out the reservoir related entries : hydro.namelist_working and one does : hydro.namelist_Lindsay

## Your Environment
Currently Loaded Modules:
  1) intel/18.0.5   2) ncl/6.6.2   3) ncarcompilers/0.5.0   4) netcdf/4.7.3   5) ncarenv/1.3   6) impi/2018.4.274   7) nco/4.7.9   8) ncview/2.1.7   9) R/3.6.0  10) arm-forge/19.1  11) python/3.6.8

**Comment by kafitzgerald** [comment]
Thanks for pointing this out. 

It's failing with the template namelist because `reservoir_persistance` is no longer a namelist option.  It's been superseded by others and wasn't updated in the template namelist.  See here: https://github.com/NCAR/wrf_hydro_nwm_public/blob/8f248ef1b6b639214ebafed41e3cfd7e4d216b76/trunk/NDHMS/OrchestratorLayer/config.f90#L111-L118 

Unfortunately, the error isn't the most descriptive either: 
>The job is stopped due to the fatal error. 
 HYDRO_nlst namelist error in read_rt_nlst

As you noted, if you remove `reservoir_persistence` or the subset of options mentioned the model will run as expected.

Given that these template namelists are largely intended (at least in my understanding) for community use, I'm inclined to just remove that section until the code is better documented and more stable. 

I know these are used in the training materials as well, so I'll hold off on bigger changes, but running through a quick test run or two with the example case(s) and these namelists made me question some of our choices for what options we include and the values those are set to.  Quite a few changes are required to get these to run for either NWM or Gridded configs.

**Comment by kafitzgerald** [comment]
This section was removed in PR#446.

Still worth thinking about how we organize template namelists, but we'll save that for another day.  

Closing.
