### ISSUE TITLE
frxst_pts_out.txt problem in version 5.1.2

### ISSUE THREAD

**Issue by Khamirak** [NCAR/wrf_hydro_nwm_public#513]
Hi 
I've encountered a new problem in wrf-hydro.
I use version 5.1.2. netcdf-c-v4.7.2 and netcdf-fortran-4.5.2
When I changed REFKDT coefficient from 0.5 to 3 in soil_param.nc ,but frxst_pts_out.txt didn't change!
Also I changed my data for another date, also frxst_pts_out.txt didn't change! 
This is a weird problem.

I have 12 hours of GFS data. Could anyone test my data with REFKDT coefficient for 0.5 and 3 in your model?
I don't know why frxst_pts_out.txt didn't change?

My input GFS files and namelists and also exported  frxst_pts_out.txt  with different  REFKDT   attached. Moreover DOMAIN and FORCING folders attached.
I would appreciate if you help me to solve this problem.

Thank you for your contribution

[DOMAIN.zip](https://github.com/NCAR/wrf_hydro_nwm_public/files/5199941/DOMAIN.zip)
[FORCING.zip](https://github.com/NCAR/wrf_hydro_nwm_public/files/5199946/FORCING.zip)
[frxst_pts_out_REFKDT=.5.txt](https://github.com/NCAR/wrf_hydro_nwm_public/files/5199952/frxst_pts_out_REFKDT.5.txt)
[frxst_pts_out_REFKDT=3.txt](https://github.com/NCAR/wrf_hydro_nwm_public/files/5199954/frxst_pts_out_REFKDT.3.txt)

[namelists.zip](https://github.com/NCAR/wrf_hydro_nwm_public/files/5199963/namelists.zip)
[input_gfs.zip](https://github.com/NCAR/wrf_hydro_nwm_public/files/5199964/input_gfs.zip)

**Comment by kafitzgerald** [comment]
A couple of thought here:
* You'll want to make sure that you're compiling the code with SPATIAL_SOIL=1 in order to read from the netCDF parameter file rather than the parameter tables
* It's also very possible that 12 hours of simulation time isn't enough to see a significant difference in your outputs

You might try running for a few days with the idealized forcing option (see documentation for details) as a test.   

For future questions regarding model configuration and usage of the model please post to the [WRF-hydro User's Forum](https://groups.google.com/a/ucar.edu/g/wrf-hydro_users) first or the [WRF-Hydro contact form](https://ral.ucar.edu/projects/wrf_hydro/contact) for more specific inquiries and requests.  

If you're confident you've found a bug in the code itself or for instance have specific features you're working on that you'd like to contribute back, here's the place.
