### ISSUE TITLE
Mismatch in min channel slope threshold

### ISSUE THREAD

**Issue by aubreyd** [NCAR/wrf_hydro_nwm_public#591]
## Expected Behavior
Matchy matchy!

## Current Behavior
Minimum slope setting appears mismatched. Why snap all slopes < 1e-4 to 1e-5?
`where(So .lt. 0.0001) So=0.00001`

## Possible Solution
Revert back to original formulation capping slopes < 1e-5 to 1e-5.

## Steps to Reproduce (for bugs)
N/A

## Your Environment
N/A

**Comment by jmccreight** [comment]
I'll reiterate comments I made in slack:

* "magic numbers" in the code lead to mistakes like this.
* The bigger point is that this parameter business just should not be in the model. The parameter business should be in the parameter files and allow the user to have complete control over the provided parameters. If there is concern about users supplying low values of bottom slope, print a warning or something else. For example, doing experiments on what the best minimum should be would require a code branch instead of just a simple set of parameter files.
