### ISSUE TITLE
module_channel_routing.f does not compile 

### ISSUE THREAD

**Issue by jbensabat** [NCAR/wrf_hydro_nwm_public#595]
Hello 
I am trying to build wrf-hydro standalone with Intel Fortran Compiler.
in module_channel_routing.f line 1225 there is a call 

              call rt_domain(did)%reservoirs(i)%ptr%run(QLAKEIP(i), QLAKEI(i), &
                   QLLAKE(i), RESHT(i), QLAKEO(i), DTCT, rt_domain(did)%final_reservoir_type(i), &
                   rt_domain(did)%reservoir_assimilated_value(i), rt_domain(did)%reservoir_assimilated_source_file(i))

that creates an error during compilation
probably because rt_domain is a function 
any help would really be appreciated.
best
jac

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version of the code used:
* Operating System and version:
* Compiler and version:
* Other relevant information:

**Comment by scrasmussen** [comment]
Hi, @jbensabat, I'm guessing that this error is occurring because you're not following the procedures to build the project. The [main project website](https://ral.ucar.edu/projects/wrf_hydro/technical-description-user-guide) has technical guides to help with installation. If you have issue following the steps in [How To Build & Run WRF-Hydro V5.1.1 in Standalone Mode](https://ral.ucar.edu/sites/default/files/public/projects/Technical%20Description%20%26amp%3B%20User%20Guides/howtobuildrunwrfhydrov511instandalonemode.pdf) please let me know and I can try to help with that. Since this and issues #596 and #597 are build issues, I will close the others ones since the issues will be addressed here.

**Comment by rcabell** [comment]
Closing for now due to inactivity - if this error occurs again, please reopen with error message text.
