### ISSUE TITLE
running WRF_HYDRO NWM with MPP_LAND 

### ISSUE THREAD

**Issue by jbensabat** [NCAR/wrf_hydro_nwm_public#714]
## Expected Behavior

when the flag of parallel processing is on (MPP_LAND) there is a call to the following function

#ifdef MPP_LAND
      call MPP_LAND_INIT()
      call MPI_COMM_RANK(HYDRO_COMM_WORLD, rank, ierr)
#else
      rank = 0
#endif

in the library hydro_mpp.lib (file mpp_land.f) the subroutine is 
  subroutine MPP_LAND_INIT(in_global_nx,in_global_ny)

so it requires the size of the grid too soon, before this data is available and this causes a crash of the code 

I suggest to either read the header before calling this function or place this call after reading the header

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version of the code used: 5.2
* Operating System and version: windows 11
* Compiler and version: intel oneAPI 2023
* Other relevant information:

**Comment by scrasmussen** [comment]
Hi @jbensabat, thank you for pointing this out. The call to `MPP_Land_init()`, without any arguments, is only used in the  Noah version, which should probably be viewed as a legacy build since NoahMP has replaced it. If you want to use Noah then I believe the [v5.0.3 version](https://github.com/NCAR/wrf_hydro_nwm_public/releases/tag/v5.0.3) might work for you. If you don't need to use Noah, I would recommend following the [CMake build instructions](https://github.com/NCAR/wrf_hydro_nwm_public/releases/tag/v5.0.3) where this issue won't be a problem.

Either way since the subroutine arguments are optional, [these statements](https://github.com/NCAR/wrf_hydro_nwm_public/blob/5d9e489fed01ed7cbd6b5680616ee37812a7137a/src/MPP/mpp_land.F#L153-L154) should be in an "if present" check. I'll work on creating a PR for that, thanks!

**Comment by jbensabat** [comment]
Good morning and thanks for your reply 
I am learning the code so I am trying various configurations including NWM.
Actually I fixed the issue by moving 

#ifdef MPP_LAND
call MPP_LAND_INIT(ix,jx)
call MPI_COMM_RANK(HYDRO_COMM_WORLD, rank, ierr)
#else
rank = 0
#endif
 after the call to call read_hrldas_hdrinfo
which provides the values of ix, jx
using the "present" function in MPP_LAND does not solve the problem as this function calls another function where explicit values of ix and jx are needed. 

there is another issue related to this option, there are two preprocessor flags MPP_LAND and _PARALLEL_
if I understand properly, MPP_LAND switches on parallel processing (MPI) so why is the purpose of _PARALLEL_ ?
is it needed ? 
best
jac
