### ISSUE TITLE
WRF Hydro mpirun

### ISSUE THREAD

**Issue by FatemehAmeri** [NCAR/wrf_hydro_nwm_public#767]
I have compiled WRF Hydro  standalone in parallel mode using the PGI compiler. When I tried to run the tests, both with one processor and with multiple processors (e.g., 8), the simulation time was the same. I came across something in the user manual (2.3 Parallelization Strategy) that says, "Currently, sequential compile is not supported, so MPI libraries are required even if running over a single core."
Does this mean that it does not support multicore processing?  I would really appreciate any help or clarification on this issue.
  The model make the diag_hydro.00000 for each core with model finished successfully........ comment that mean it was successfully run
I just want to make sure it is correctly compiled and use all cores

**Comment by aubreyd** [comment]
This was answered through our help ticketing system.

"WRF-Hydro requires an MPI library. You can run the model using 1 core or hundreds. Depending on the size of the domain, adding more cores may not help the speed since there is overhead in communicating between the processors. So small domains (like our test case) may not see runtime benefits from using more than 1 or 2 processors. However, for larger domains you will definitely see runtime speedups."
