### ISSUE TITLE
Unit labels on some CHRTOUT_DOMAIN variables

### ISSUE THREAD

**Issue by dblodgett-usgs** [NCAR/wrf_hydro_nwm_public#77]
In this file: https://ral.ucar.edu/sites/default/files/public/WRFHydroV5_OutputVariableMatrix_V5.pdf 
qBtmVertRunoff is labeled as having units of m3 -- @mccreigh confirmed that it should be m3/s. 

In the V1.2 retrospective output sourced from Amazon, we are also seeing m3 units on qSfcLatRunoff and qBucket. 

See #76 for code fix of qBtmVertRunoff. It sounds like the others were already fixed in code (since the v1.2 retro was run). 

The label in the pdf matrix linked above will also need attention.

Closure criteria, units on these three are correct in code and updated in documentation. 

Note that I did not find the units for these variables in the wrf-hydro manual so -- probably no updated needed there.

**Comment by kafitzgerald** [comment]
I just talked to @jmccreight and there was a bit of confusion on our end.  In the NWM configuration (the only configuration that allow for these outputs), qBtmVertRunoff is qin_gwsubbas and has units of m^3 accumulated over the timestep so should be correct in the current code + output variable matrix.  

Unfortunately, (as suggested above) it looks the initial unit fix on these terms went in after v1.2 code and corresponding retrospective simulation.

**Comment by mkhongtamu** [comment]
Hi, My name is Minki Hong. Now I am currently attending the CUAHSI summer institute and working with groundwater team. I just want to add a comment here. I agree with that qBtmVertRunoff is qin_gwsubbas in the NWM, however, the qin_gwsubbas is not accumulated over the timestep so it is not volume. 

     qin_gwsubbas(bas) = net_perc(bas)/1000.* &
                         ct_bas(bas)*basns_area(bas)/DT    !units (m^3/s)

The above equation is the code in NWM calculating qin_gwsubbas for each bucket. As you can see, qin_gwsubbas is divided by DT (delta T) so that I think qin_gwsubbas should have CMS unit.

**Comment by kafitzgerald** [comment]
Thanks for bringing this up.  

The code mentioned above is within the `simp_gw_buck` subroutine which is used when user defined mapping is off (UDMAP=0).  The NWM configuration of WRF-Hydro has user defined mapping turned on and the units for qin_gwsubbas are different (subroutine: `simp_gw_buck_nhd` within the same module).    

This is no doubt a bit confusing and has been logged in issue #78.
